### ISSUE TITLE
Progress!

### ISSUE THREAD

**Issue by adaster98** [Ratismal/Exchequer#2]
Hi Ratismal
I am really interested in this project! Shame you have no had much progress on it lately!
I got my dev stripping down and updating payday to 1.8.8 at the moment but this would be a million times better to have running!

I was just wondering if you ever plan to finish this :)
BTW Please add me on Skype: markthgirw

**Comment by Ratismal** [comment]
I'm planning on completing it, but my time has been occupied by university and my other projects (looking into modding).
